repos:
- repo: local
  hooks:
  - id: pycodestyle
    name: pycodestyle
    entry: .venv/bin/pycodestyle
    language: system
    args: [
        "--ignore=E501"
      ]
    types: [python]
    files: ^app/

  - id: pylint
    name: pylint
    entry: .venv/bin/pylint
    language: system
    args: [
        "--rcfile=./.config/.pylintrc"
      ]
    types: [python]
    files: ^app/
